package com.example.searchviewbottomnav

object Fruits {
    val fruitList = listOf(
            "Apple",
            "Apricot",
            "Apricots",
            "Asian Pear",
            "Banana",
            "Blackberry",
            "Blueberries",
            "Boysenberries",
            "Cantaloupe",
            "Casaba Melon",
            "Cherries",
            "Coconut",
            "Cranberry",
            "Currents",
            "Dates",
            "Durian",
            "Fig",
            "Gooseberry",
            "Grapefruit",
            "Grapes",
            "Guava",
            "Honeydew Melon",
            "Jackfruit",
            "Kiwifruit",
            "Kumquat",
            "Lemon",
            "Lychee",
            "Mandarin Oranges",
            "Mango",
            "Mangosteen",
            "Melon",
            "Mulberry",
            "Nectarine",
            "Orange",
            "Papaya",
            "Passion Fruit",
            "Peach",
            "Pear",
            "Pineapple",
            "Plum",
            "Pomegranate",
            "Pomelo",
            "Prune",
            "Quince",
            "Raspberries",
            "Rhubarb",
            "Strawberries",
            "Tangerines",
            "Watermelon"

            )
}